# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import time
import logging
import wandb
import torch
import torch.nn.functional as F
from torch.cuda.amp import autocast
from third_party.open_clip.clip import tokenize
from utils import is_master


def unwrap_model(model):
    return model.module if hasattr(model, "module") else model


def move_to_device(x, gpu):
    if isinstance(x, torch.Tensor):
        return x.cuda(gpu, non_blocking=True) if gpu is not None else x
    return x


def tokenize_to_device(texts, args):
    """
    Support both:
      1) raw texts: list[str] / tuple[str] / str
      2) pre-tokenized tensor: Tensor[B, L]

    Returns:
      tokens: LongTensor[B, L]
    """
    # Case 1: already token ids
    if isinstance(texts, torch.Tensor):
        tokens = texts
        if args.gpu is not None:
            tokens = tokens.cuda(args.gpu, non_blocking=True)
        return tokens.long()

    # Case 2: single string
    if isinstance(texts, str):
        texts = [texts]

    # Case 3: list/tuple -> maybe strings, maybe tensors
    if isinstance(texts, (list, tuple)):
        if len(texts) == 0:
            raise ValueError("Empty text batch.")

        first = texts[0]

        # list[str]
        if isinstance(first, str):
            tokens = tokenize(list(texts))
            if args.gpu is not None:
                tokens = tokens.cuda(args.gpu, non_blocking=True)
            return tokens.long()

        # list[tensor]
        if isinstance(first, torch.Tensor):
            tokens = torch.stack(list(texts), dim=0)
            if args.gpu is not None:
                tokens = tokens.cuda(args.gpu, non_blocking=True)
            return tokens.long()

    raise TypeError(
        f"Unsupported texts type for tokenization: {type(texts)}. "
        f"Example value type inside batch: "
        f"{type(texts[0]) if isinstance(texts, (list, tuple)) and len(texts) > 0 else 'N/A'}"
    )


def encode_text_batch(model, texts, args):
    """
    Standard text encoding with CLIP text encoder.
    texts -> token ids -> text features
    """
    tokens = tokenize_to_device(texts, args)
    text_features = model.encode_text(tokens)
    return text_features

def encode_image_batch(model, images, args):
    """
    Standard text encoding with CLIP text encoder.
    texts -> token ids -> text features
    """
    image_features = model.encode_image(images)
    return image_features


def apply_global_start_noise(features, args):
    noise_std = getattr(args, "global_start_noise_std", 0.0)
    if noise_std <= 0:
        return features
    return features + torch.randn_like(features) * noise_std


def get_text_features(model, token_features, args):
    """
    Image-derived token features -> CLIP text encoder.

    This follows the original project logic:
        text prompt: "a photo of"
        token_features: generated by img2text(image_features)
        final text feature: model.encode_text_img(text, token_features)
    """
    text = tokenize("a photo of")
    if args.gpu is not None:
        text = text.cuda(args.gpu, non_blocking=True)

    text = text.view(1, -1)
    text = text.repeat(token_features.size(0), 1).long()

    text_features = model.encode_text_img(text, token_features)
    return text_features


def encode_image_via_img2text(model, img2text, images, args):
    """
    reference image -> image encoder -> img2text -> text encoder
    """
    image_features = model.encode_image(images)
    token_features = img2text(image_features)
    text_features = get_text_features(model, token_features, args)
    return text_features


def _normalize_feature(x, eps=1e-6):
    return x / x.norm(dim=-1, keepdim=True).clamp(min=eps)


def _sphere_expmap_step(x, v, dt, eps=1e-6):
    x_unit = _normalize_feature(x, eps=eps)
    v_tan = v - (v * x_unit).sum(dim=-1, keepdim=True) * x_unit
    speed = v_tan.norm(dim=-1, keepdim=True).clamp(min=eps)
    theta = dt * speed
    direction = v_tan / speed
    x_next = torch.cos(theta) * x_unit + torch.sin(theta) * direction
    return _normalize_feature(x_next, eps=eps)


def encode_pic2word_composed_feature(model, img2text, images, texts, args):
    text_tokens = tokenize_to_device(texts, args)
    split_text = getattr(args, "global_flow_pic2word_marker", "*")
    split_token_id = tokenize([split_text])[0][1].item()

    if not torch.all((text_tokens == split_token_id).any(dim=1)):
        raise ValueError(
            "global_flow_compose_method='pic2word' requires every text prompt to "
            f"contain the marker token {split_text!r}."
        )

    image_features = model.encode_image(images)
    image_features = _normalize_feature(image_features)
    query_image_tokens = img2text(image_features)
    composed_feature = model.encode_text_img_retrieval(
        text_tokens,
        query_image_tokens,
        split_ind=split_token_id,
        repeat=False,
    )
    return composed_feature


def build_global_flow_feature(model, img2text, ref_images, texts, args, source, text_weight, image_weight):
    source = source.lower()
    if source == "text":
        feature = encode_text_batch(model, texts, args)
    elif source == "image":
        feature = encode_image_batch(model, ref_images, args)
    elif source == "composed":
        compose_method = getattr(args, "global_flow_compose_method", "add").lower()
        if compose_method == "pic2word":
            feature = encode_pic2word_composed_feature(model, img2text, ref_images, texts, args)
        else:
            text_feature = encode_text_batch(model, texts, args)
            image_feature = encode_image_via_img2text(model, img2text, ref_images, args)
            feature = text_weight * text_feature + image_weight * image_feature
            if compose_method == "mean":
                denom = max(text_weight + image_weight, 1e-6)
                feature = feature / denom
            elif compose_method != "add":
                raise ValueError(f"Unsupported global_flow_compose_method: {compose_method}")
    else:
        raise ValueError(f"Unsupported global flow feature source: {source}")

    return _normalize_feature(feature)


def flow_matching_inference(flow_net, q, e_m=None, num_steps=4, step_normalize=True, step_norm_type="l2"):
    q = _normalize_feature(q)
    if e_m is not None:
        e_m = _normalize_feature(e_m)

    x_t = q.clone()
    x0 = q.clone()
    batch_size = q.size(0)
    dt = 1.0 / num_steps

    for k in range(num_steps):
        t = torch.full(
            (batch_size, 1),
            k / num_steps,
            device=q.device,
            dtype=q.dtype,
        )
        delta = x_t - x0
        velocity = flow_net(x_t, delta=delta, e_m=e_m, t=t)
        velocity = torch.tanh(velocity)
        if step_normalize:
            if step_norm_type == "expmap":
                x_t = _sphere_expmap_step(x_t, velocity, dt=dt)
            else:
                x_t = _normalize_feature(x_t + dt * velocity)
        else:
            x_t = x_t + dt * velocity

    return x_t


def parse_batch_for_flow(batch):
    """
    Expected batch format:

    1) dict:
        {
            "ref_images": ...,
            "mod_texts": ...,
            "target_texts": ...
        }

    2) tuple/list:
        (ref_images, mod_texts, target_texts)

    Returns:
        ref_images, mod_texts, target_texts
    """
    if isinstance(batch, dict):
        ref_images = batch["ref_images"]
        mod_texts = batch["mod_texts"]
        target_texts = batch["target_texts"]
        return ref_images, mod_texts, target_texts

    if isinstance(batch, (list, tuple)):
        if len(batch) < 3:
            raise ValueError(
                "Flow matching training expects batch to contain at least "
                "(ref_images, mod_texts, target_texts)."
            )
        return batch[0], batch[1], batch[2]

    raise TypeError(f"Unsupported batch type: {type(batch)}")


def parse_val_batch_for_flow(batch):
    """
    Validation batch parser.

    Supports:
      1) (ref_images, mod_texts, target_texts)
      2) (ref_images, target_images, mod_texts, target_texts)
      3) dict with keys ref_images/mod_texts/target_texts

    Returns:
        ref_images, target_images(or None), mod_texts, target_texts
    """
    if isinstance(batch, dict):
        return batch["ref_images"], batch.get("target_images", None), batch["mod_texts"], batch["target_texts"]

    if isinstance(batch, (list, tuple)):
        if len(batch) == 3:
            # FashionIQ(caps) returns (ref_images, target_images, modification_text)
            if torch.is_tensor(batch[1]):
                return batch[0], batch[1], batch[2], None
            return batch[0], None, batch[1], batch[2]
        if len(batch) >= 4:
            return batch[0], batch[1], batch[2], batch[3]

    raise TypeError(f"Unsupported validation batch type: {type(batch)}")


def validate(model, img2text, flow_net, criterion, data, epoch, args, writer=None):
    if "val" not in data:
        return None

    val_loader = data["val"].dataloader
    if val_loader is None:
        return None
    if isinstance(val_loader, (list, tuple)) and len(val_loader) == 2:
        source_loader, target_loader = val_loader[0], val_loader[1]
    else:
        source_loader = val_loader
        target_loader = getattr(source_loader, "target_dataloader", None)

    m = unwrap_model(model)
    it = unwrap_model(img2text)
    flow = unwrap_model(flow_net)

    m.eval()
    it.eval()
    flow.eval()

    all_query_features = []
    all_target_features = []
    all_answer_names = []
    gallery_features = None
    gallery_names = None

    if target_loader is not None:
        gallery_features_list = []
        gallery_names_list = []
        with torch.no_grad():
            for target_batch in target_loader:
                gallery_images, gallery_paths = target_batch
                gallery_images = move_to_device(gallery_images, args.gpu)
                feats = _normalize_feature(encode_image_batch(m, gallery_images, args))
                gallery_features_list.append(feats.detach().cpu())
                gallery_names_list.extend(list(gallery_paths))
        if len(gallery_features_list) > 0:
            gallery_features = F.normalize(torch.cat(gallery_features_list, dim=0), dim=-1)
            gallery_names = gallery_names_list

    with torch.no_grad():
        for batch in source_loader:
            if isinstance(batch, (list, tuple)) and len(batch) >= 5:
                all_answer_names.extend(list(batch[4]))
            ref_images, target_images, mod_texts, target_texts = parse_val_batch_for_flow(batch)
            ref_images = move_to_device(ref_images, args.gpu)
            if target_images is not None:
                target_images = move_to_device(target_images, args.gpu)

            if args.loss_type != "global":
                raise ValueError(f"Unsupported loss_type: {args.loss_type}")
            q = build_global_flow_feature(
                model=m,
                img2text=it,
                ref_images=ref_images,
                texts=mod_texts,
                args=args,
                source=getattr(args, "global_flow_start_source", "text"),
                text_weight=getattr(args, "global_flow_start_text_weight", 1.0),
                image_weight=getattr(args, "global_flow_start_image_weight", 1.0),
            )
            use_condition = getattr(args, "global_flow_conditioning", "enabled") == "enabled"
            e_m = None
            if use_condition:
                e_m = build_global_flow_feature(
                    model=m,
                    img2text=it,
                    ref_images=ref_images,
                    texts=mod_texts,
                    args=args,
                    source=getattr(args, "global_flow_condition_source", "image"),
                    text_weight=getattr(args, "global_flow_condition_text_weight", 1.0),
                    image_weight=getattr(args, "global_flow_condition_image_weight", 1.0),
                )
            if target_texts is not None:
                val_target_features = _normalize_feature(encode_text_batch(m, target_texts, args))
            elif target_images is not None:
                val_target_features = _normalize_feature(encode_image_batch(m, target_images, args))
            else:
                raise ValueError("Validation batch must provide target_texts or target_images.")

            q = apply_global_start_noise(q, args)
            val_query_features = flow_matching_inference(
                flow_net=flow,
                q=q,
                e_m=e_m,
                num_steps=getattr(args, "flow_num_steps", 16),
                step_normalize=getattr(args, "flow_step_normalize", True),
                step_norm_type=getattr(args, "flow_step_norm_type", "l2"),
            )

            all_query_features.append(val_query_features.detach().cpu())
            all_target_features.append(val_target_features.detach().cpu())

    if len(all_query_features) == 0:
        return None

    val_metrics = {}
    if gallery_features is not None and len(all_query_features) > 0 and len(all_answer_names) > 0:
        query_features = F.normalize(torch.cat(all_query_features, dim=0), dim=-1)
        logits = query_features @ gallery_features.t()
        ranking = torch.argsort(logits, dim=-1, descending=True)

        name_to_index = {name: idx for idx, name in enumerate(gallery_names)}
        gt_index = torch.tensor([name_to_index[name] for name in all_answer_names], dtype=torch.long)
        gt_pos = torch.where(ranking == gt_index.view(-1, 1))[1]

        for k in [1, 5, 10, 50, 100]:
            k_eff = min(k, ranking.size(1))
            val_metrics[f"R@{k}"] = (gt_pos < k_eff).float().mean().item() * 100.0
    elif len(all_query_features) > 0 and len(all_target_features) > 0:
        query_features = F.normalize(torch.cat(all_query_features, dim=0), dim=-1)
        target_features = F.normalize(torch.cat(all_target_features, dim=0), dim=-1)
        logits = query_features @ target_features.t()
        ranking = torch.argsort(logits, dim=-1, descending=True)
        gt = torch.arange(ranking.size(0)).view(-1, 1)
        gt_pos = torch.where(ranking == gt)[1]

        for k in [1, 5, 10, 50, 100]:
            k_eff = min(k, ranking.size(1))
            val_metrics[f"R@{k}"] = (gt_pos < k_eff).float().mean().item() * 100.0

    if is_master(args):
        metric_text = "\t".join([f"{k}: {v:.4f}" for k, v in val_metrics.items()])
        if metric_text:
            logging.info(f"Validation Epoch: {epoch}\t{metric_text}")
        else:
            logging.info(f"Validation Epoch: {epoch}\tNo retrieval metrics were produced.")
        if writer is not None:
            for key, value in val_metrics.items():
                writer.add_scalar(f"val/{key}", value, epoch)
        if args.wandb:
            wandb_payload = {"epoch": epoch}
            for key, value in val_metrics.items():
                wandb_payload[f"val/{key}"] = value
            wandb.log(wandb_payload)

    return val_metrics


def train(model, img2text, flow_net, criterion, data, epoch, optimizer, scaler, scheduler, args, writer=None):
    os.environ["WDS_EPOCH"] = str(epoch)

    # frozen modules
    model.eval()
    img2text.eval()
    flow_net.train()

    dataloader, sampler = data["train"].dataloader, data["train"].sampler

    if args.distributed and sampler is not None:
        sampler.set_epoch(epoch)

    num_batches_per_epoch = dataloader.num_batches
    end = time.time()

    for i, batch in enumerate(dataloader):
        step = num_batches_per_epoch * epoch + i
        if scheduler is not None:
            scheduler(step)

        optimizer.zero_grad()

        # --------------------------------------------------
        # 1. parse batch
        # --------------------------------------------------
        ref_images, mod_texts, target_texts = parse_batch_for_flow(batch)
        # ref_images, target_images, mod_texts = parse_batch_for_flow(batch)
        
        # if i == 0 and is_master(args):
        #     logging.info(f"type(batch) = {type(batch)}")
        #     logging.info(f"type(ref_images) = {type(ref_images)}")
        #     logging.info(f"type(mod_texts) = {type(mod_texts)}")
        #     logging.info(f"type(target_texts) = {type(target_texts)}")

        #     if isinstance(mod_texts, (list, tuple)) and len(mod_texts) > 0:
        #         logging.info(f"type(mod_texts[0]) = {type(mod_texts[0])}")
        #     if isinstance(target_texts, (list, tuple)) and len(target_texts) > 0:
        #         logging.info(f"type(target_texts[0]) = {type(target_texts[0])}")
        ref_images = move_to_device(ref_images, args.gpu)

        data_time = time.time() - end

        m = unwrap_model(model)
        it = unwrap_model(img2text)

        # --------------------------------------------------
        # 2. encode features
        #
        # q   : configurable start embedding
        # e_m : optional configurable condition embedding
        # y   : target/generated caption -> text encoder
        # --------------------------------------------------
        with torch.no_grad():
            if args.loss_type != "global":
                raise ValueError(f"Unsupported loss_type: {args.loss_type}")
            q = build_global_flow_feature(
                model=m,
                img2text=it,
                ref_images=ref_images,
                texts=mod_texts,
                args=args,
                source=getattr(args, "global_flow_start_source", "text"),
                text_weight=getattr(args, "global_flow_start_text_weight", 1.0),
                image_weight=getattr(args, "global_flow_start_image_weight", 1.0),
            )
            use_condition = getattr(args, "global_flow_conditioning", "enabled") == "enabled"
            e_m = None
            if use_condition:
                e_m = build_global_flow_feature(
                    model=m,
                    img2text=it,
                    ref_images=ref_images,
                    texts=mod_texts,
                    args=args,
                    source=getattr(args, "global_flow_condition_source", "image"),
                    text_weight=getattr(args, "global_flow_condition_text_weight", 1.0),
                    image_weight=getattr(args, "global_flow_condition_image_weight", 1.0),
                )
            y = encode_text_batch(m, target_texts, args)

            q = apply_global_start_noise(q, args)
            q = _normalize_feature(q)
            y = _normalize_feature(y)
            if e_m is not None:
                e_m = _normalize_feature(e_m)

        # --------------------------------------------------
        # 3. flow matching loss
        # --------------------------------------------------
        if args.precision == "amp":
            with autocast():
                if args.loss_type != "global":
                    raise ValueError(f"Unsupported loss_type: {args.loss_type}")
                loss_dict = criterion(q, y, e_m)
                total_loss = loss_dict["loss"]

            scaler.scale(total_loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            if args.loss_type != "global":
                raise ValueError(f"Unsupported loss_type: {args.loss_type}")
            loss_dict = criterion(q, y, e_m)
            total_loss = loss_dict["loss"]
            total_loss.backward()
            optimizer.step()

        batch_time = time.time() - end
        end = time.time()

        # --------------------------------------------------
        # 4. logging
        # --------------------------------------------------
        if is_master(args) and (i % 100) == 0:
            batch_size = ref_images.size(0)
            num_samples = i * batch_size * args.world_size
            samples_per_epoch = dataloader.num_samples
            percent_complete = 100.0 * i / num_batches_per_epoch

            logging.info(
                f"Train Epoch: {epoch} [{num_samples}/{samples_per_epoch} ({percent_complete:.0f}%)]\t"
                f"Loss: {total_loss.item():.6f}\t"
                f"FM: {loss_dict['loss_fm'].item():.6f}\t"
                f"End: {loss_dict['loss_end'].item():.6f}\t"
                f"Ret: {loss_dict['loss_ret'].item():.6f}\t"
                f"Data (t) {data_time:.3f}\tBatch (t) {batch_time:.3f}\t"
                f"LR: {optimizer.param_groups[0]['lr']:.6e}"
            )

            timestep = epoch * num_batches_per_epoch + i
            log_data = {
                "loss": total_loss.item(),
                "loss_fm": loss_dict["loss_fm"].item(),
                "loss_end": loss_dict["loss_end"].item(),
                "loss_ret": loss_dict["loss_ret"].item(),
                "data_time": data_time,
                "batch_time": batch_time,
                "lr": optimizer.param_groups[0]["lr"],
            }

            for name, val in log_data.items():
                tag = "train/" + name
                if writer is not None:
                    writer.add_scalar(tag, val, timestep)
                if args.wandb:
                    wandb.log({tag: val, "step": timestep})
