# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import time
import logging
import wandb
import torch
from torch.cuda.amp import autocast
from third_party.open_clip.clip import tokenize
from utils import is_master


def unwrap_model(model):
    return model.module if hasattr(model, "module") else model


def move_to_device(x, gpu):
    if isinstance(x, torch.Tensor):
        return x.cuda(gpu, non_blocking=True) if gpu is not None else x
    return x


def tokenize_to_device(texts, args):
    """
    Support both:
      1) raw texts: list[str] / tuple[str] / str
      2) pre-tokenized tensor: Tensor[B, L]

    Returns:
      tokens: LongTensor[B, L]
    """
    # Case 1: already token ids
    if isinstance(texts, torch.Tensor):
        tokens = texts
        if args.gpu is not None:
            tokens = tokens.cuda(args.gpu, non_blocking=True)
        return tokens.long()

    # Case 2: single string
    if isinstance(texts, str):
        texts = [texts]

    # Case 3: list/tuple -> maybe strings, maybe tensors
    if isinstance(texts, (list, tuple)):
        if len(texts) == 0:
            raise ValueError("Empty text batch.")

        first = texts[0]

        # list[str]
        if isinstance(first, str):
            tokens = tokenize(list(texts))
            if args.gpu is not None:
                tokens = tokens.cuda(args.gpu, non_blocking=True)
            return tokens.long()

        # list[tensor]
        if isinstance(first, torch.Tensor):
            tokens = torch.stack(list(texts), dim=0)
            if args.gpu is not None:
                tokens = tokens.cuda(args.gpu, non_blocking=True)
            return tokens.long()

    raise TypeError(
        f"Unsupported texts type for tokenization: {type(texts)}. "
        f"Example value type inside batch: "
        f"{type(texts[0]) if isinstance(texts, (list, tuple)) and len(texts) > 0 else 'N/A'}"
    )


def encode_text_batch(model, texts, args):
    """
    Standard text encoding with CLIP text encoder.
    texts -> token ids -> text features
    """
    tokens = tokenize_to_device(texts, args)
    text_features = model.encode_text(tokens)
    return text_features

def encode_image_batch(model, images, args):
    """
    Standard text encoding with CLIP text encoder.
    texts -> token ids -> text features
    """
    image_features = model.encode_image(images)
    return image_features

def get_text_features(model, token_features, args):
    """
    Image-derived token features -> CLIP text encoder.

    This follows the original project logic:
        text prompt: "a photo of"
        token_features: generated by img2text(image_features)
        final text feature: model.encode_text_img(text, token_features)
    """
    text = tokenize("a photo of")
    if args.gpu is not None:
        text = text.cuda(args.gpu, non_blocking=True)

    text = text.view(1, -1)
    text = text.repeat(token_features.size(0), 1).long()

    text_features = model.encode_text_img(text, token_features)
    return text_features


def encode_image_via_img2text(model, img2text, images, args):
    """
    reference image -> image encoder -> img2text -> text encoder
    """
    image_features = model.encode_image(images)
    token_features = img2text(image_features)
    text_features = get_text_features(model, token_features, args)
    return text_features


def parse_batch_for_flow(batch):
    """
    Expected batch format:

    1) dict:
        {
            "ref_images": ...,
            "mod_texts": ...,
            "target_texts": ...
        }

    2) tuple/list:
        (ref_images, mod_texts, target_texts)

    Returns:
        ref_images, mod_texts, target_texts
    """
    if isinstance(batch, dict):
        ref_images = batch["ref_images"]
        mod_texts = batch["mod_texts"]
        target_texts = batch["target_texts"]
        return ref_images, mod_texts, target_texts

    if isinstance(batch, (list, tuple)):
        if len(batch) < 3:
            raise ValueError(
                "Flow matching training expects batch to contain at least "
                "(ref_images, mod_texts, target_texts)."
            )
        return batch[0], batch[1], batch[2]

    raise TypeError(f"Unsupported batch type: {type(batch)}")


def train(model, img2text, flow_net, criterion, data, epoch, optimizer, scaler, scheduler, args, writer=None):
    os.environ["WDS_EPOCH"] = str(epoch)

    # frozen modules
    model.eval()
    img2text.eval()
    flow_net.train()

    dataloader, sampler = data["train"].dataloader, data["train"].sampler

    if args.distributed and sampler is not None:
        sampler.set_epoch(epoch)

    num_batches_per_epoch = dataloader.num_batches
    end = time.time()

    for i, batch in enumerate(dataloader):
        step = num_batches_per_epoch * epoch + i
        if scheduler is not None:
            scheduler(step)

        optimizer.zero_grad()

        # --------------------------------------------------
        # 1. parse batch
        # --------------------------------------------------
        ref_images, mod_texts, target_texts = parse_batch_for_flow(batch)
        # ref_images, target_images, mod_texts = parse_batch_for_flow(batch)
        
        # if i == 0 and is_master(args):
        #     logging.info(f"type(batch) = {type(batch)}")
        #     logging.info(f"type(ref_images) = {type(ref_images)}")
        #     logging.info(f"type(mod_texts) = {type(mod_texts)}")
        #     logging.info(f"type(target_texts) = {type(target_texts)}")

        #     if isinstance(mod_texts, (list, tuple)) and len(mod_texts) > 0:
        #         logging.info(f"type(mod_texts[0]) = {type(mod_texts[0])}")
        #     if isinstance(target_texts, (list, tuple)) and len(target_texts) > 0:
        #         logging.info(f"type(target_texts[0]) = {type(target_texts[0])}")
        ref_images = move_to_device(ref_images, args.gpu)

        data_time = time.time() - end

        m = unwrap_model(model)
        t = unwrap_model(img2text)

        # --------------------------------------------------
        # 2. encode features
        #
        # q   : reference image -> img2text -> text encoder
        # e_m : modification text -> text encoder
        # y   : target/generated caption -> text encoder
        # --------------------------------------------------
        with torch.no_grad():
            # reverse
            # e_m = encode_image_via_img2text(m, t, ref_images, args)  # [B, D]
            e_m = encode_image_batch(m, ref_images, args)
            q = encode_text_batch(m, mod_texts, args)            # [B, D]
            y = encode_text_batch(m, target_texts, args)           # [B, D]

            # q = encode_image_batch(m, ref_images, args)
            # e_m = encode_text_batch(m, mod_texts, args)
            # y = encode_image_batch(m, target_images, args)
            

            # normalize for stable metric alignment
            q = q / q.norm(dim=-1, keepdim=True).clamp(min=1e-6)
            e_m = e_m / e_m.norm(dim=-1, keepdim=True).clamp(min=1e-6)
            y = y / y.norm(dim=-1, keepdim=True).clamp(min=1e-6)

        # --------------------------------------------------
        # 3. flow matching loss
        # --------------------------------------------------
        if args.precision == "amp":
            with autocast():
                loss_dict = criterion(q, y, e_m)
                total_loss = loss_dict["loss"]

            scaler.scale(total_loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            loss_dict = criterion(q, y, e_m)
            total_loss = loss_dict["loss"]
            total_loss.backward()
            optimizer.step()

        batch_time = time.time() - end
        end = time.time()

        # --------------------------------------------------
        # 4. logging
        # --------------------------------------------------
        if is_master(args) and (i % 100) == 0:
            batch_size = q.size(0)
            num_samples = i * batch_size * args.world_size
            samples_per_epoch = dataloader.num_samples
            percent_complete = 100.0 * i / num_batches_per_epoch

            logging.info(
                f"Train Epoch: {epoch} [{num_samples}/{samples_per_epoch} ({percent_complete:.0f}%)]\t"
                f"Loss: {total_loss.item():.6f}\t"
                f"FM: {loss_dict['loss_fm'].item():.6f}\t"
                f"End: {loss_dict['loss_end'].item():.6f}\t"
                f"Ret: {loss_dict['loss_ret'].item():.6f}\t"
                f"Data (t) {data_time:.3f}\tBatch (t) {batch_time:.3f}\t"
                f"LR: {optimizer.param_groups[0]['lr']:.6e}"
            )

            timestep = epoch * num_batches_per_epoch + i
            log_data = {
                "loss": total_loss.item(),
                "loss_fm": loss_dict["loss_fm"].item(),
                "loss_end": loss_dict["loss_end"].item(),
                "loss_ret": loss_dict["loss_ret"].item(),
                "data_time": data_time,
                "batch_time": batch_time,
                "lr": optimizer.param_groups[0]["lr"],
            }

            for name, val in log_data.items():
                tag = "train/" + name
                if writer is not None:
                    writer.add_scalar(tag, val, timestep)
                if args.wandb:
                    wandb.log({tag: val, "step": timestep})